name: Nieuwe functionaliteit
description: Template voor nieuwe features
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Omschrijving
      description: Beschrijf de nieuwe functionaliteit.
    validations:
      required: true